### ISSUE TITLE
Warehouse map and world files

### ISSUE THREAD

**Issue by giulianodejulio** [blackcoffeerobotics/gazebo-ros-actor-plugin#6]
Hello,

I am trying to use your Gazebo plugin to control actors. Could you please kindly provide the word file and the map files (pgm and yaml) of the world shown in this video ( https://www.youtube.com/watch?v=2QTtwOBGDFg ) ?

Thanks a lot!

**Comment by ggupta9777** [comment]
@giulianodejulio We created a custom world for one of our projects. While we are not in a position to currently release the world and map files, I encourage you to refer to [ARIAC](https://github.com/usnistgov/ARIAC) competitions of the past. We took heavy inspiration from their worlds to create the video.

Additionally, you can find a similar (but smaller) world and map files in another one of our repos, here - https://github.com/blackcoffeerobotics/bcr_bot/

**Comment by giulianodejulio** [comment]
Got it, thanks for your time!
